apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot-app
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # You can use LoadBalancer or NodePort depending on your need

